`ifndef CONTROL_SIGNAL
`define CONTROL_SIGNAL

`define REG_FILE_WRITE_SRC_WIDTH 2
`define REG_FILE_WRITE_SRC_MEM 2'b00
`define REG_FILE_WRITE_SRC_EX 2'b01
`define REG_FILE_WRITE_SRC_BYTE 2'b10

`endif