`ifndef CONTROL_STATE_DEFINES
`define CONTROL_STATE_DEFINES

`define CONTROL_STATE_FETCH 		4'b0000
`define CONTROL_STATE_DECODE 		4'b0001
`define CONTROL_STATE_EXECUTE		4'b0010
`define CONTROL_STATE_MEMORY		4'b0011
`define CONTROL_STATE_WRITEBACK		4'b0100

`endif