`ifndef XEDGCOL_INSTR_DEFINES
`define XEDGCOL_INSTR_DEFINES

// Define Widths
`define XEDGCOL_INSTR_WIDTH 32
`define XEDGCOL_INSTR_OPCODE_WIDTH 3
`define XEDGCOL_INSTR_REG_WIDTH 3

// Define Ranges
`define XEDGCOL_INSTR_RD_RANGE  5:3
`define XEDGCOL_INSTR_OPCODE_RANGE 2:0
`define XEDGCOL_INSTR_IMM_RANGE 31:6

`endif
